name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Каждый день в 00:00 UTC
  workflow_dispatch:     # Можно запускать вручную

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger stats update
        run: |
          git commit --allow-empty -m "🔄 Auto-update stats [skip ci]"
          git push